### ISSUE TITLE
Leasebacks created for whole season don't distribute to all games - 1.5 weeks

### ISSUE THREAD

**Issue by cflsdeboer** [cfl/issues_aims#17]
Incremental leases properly being mapped into granular assets within view_promises (Calgary selected a full season scope for their leaseback of Sideline LEDs but the quantity didn’t multiply across all games in view_promises)

**Comment by ereyescfl** [comment]
10/13 Update
This was identified as a data Quality Issue which should get Q4 Prioritization if possible. @cflsdeboer @sareena12 
Since this is a bug ER would advocate for fixing this as soon as we can 

User Story:
As a, CFL team member
I want, to be able to use the TPTD dashboards as a way to take stock of which assets we have leased back incrementally from the league and what those leasebacks cost our club
So that, we can verify key information that we need in order to operate our sponsorship practice

Confluence Link: https://cflnetwork.atlassian.net/wiki/spaces/DT/pages/2296872975/Milestone+3+-+Requirements+-+MVP+Dashboard+-+Incremental+Enhancements+-+v+1.2+-+2022
